version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - .env

  rtsp-simple-server:
    image:
    platform: linux/amd64
    ports:
      - "8554:8554"
    networks:
      - app-network

  rtsp-to-web:
    image: ghcr.io/deepch/rtsptoweb:latest
    platform: linux/amd64
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
